Repository Homebrew/homebrew-livecheck, pull requests merged in 2020-04, with the labels that each got.

#310 Skip formulae with gist.github.com stable URL
  cmd/livecheck.rb
Labels: discussion, stale

#312 syck: add livecheckable to skip
  Livecheckables/syck.rb
Labels: stale

#525 nng: add livecheckable
  Livecheckables/nng.rb
Labels: do not merge

#526 ngt: add livecheckable
  Livecheckables/ngt.rb
Labels: do not merge

#532 ocproxy: add livecheckable
  Livecheckables/ocproxy.rb
Labels: do not merge
